version: "3"
services:

  poll:
    build: ./poll
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5000:80"
    depends_on:
      - redis
    networks:
      - poll-tier
    restart: always

  redis:
    image: redis:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    restart: always


  worker:
    build: ./worker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - redis
      - poll
    networks:
      - back-tier
    restart: always

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - type: volume
        source: db-data
        target: /var/lib/mysql/data
    networks:
      - result-tier
      - back-tier
    restart: always

  result:
    build: ./result
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5001:80"
    depends_on:
      - db
    networks:
      - result-tier
    restart: always

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:
